Aqui está um código simples com sklearn para testar a execução de Python no Codespace com uma Decision Tree:

In [3]:
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

# Carregar o dataset Iris
iris = load_iris()
X = iris.data
y = iris.target

# Dividir o dataset em treinamento e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Criar uma Decision Tree
clf = DecisionTreeClassifier(random_state=42)

# Treinar a Decision Tree
clf.fit(X_train, y_train)

# Prever as classes para o conjunto de teste
y_pred = clf.predict(X_test)

# Imprimir a precisão da Decision Tree
print("Precisão:", clf.score(X_test, y_test))

Precisão : 1.0


# Exercício 1

In [1]:
from sklearn.datasets import load_digits
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
import pandas as pd
import pickle as pk
import matplotlib.pyplot as plt
import seaborn as sns


X = load_digits().data
y = load_digits().target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0, stratify=y)

clf = tree.DecisionTreeClassifier(max_depth=None)
model1 = clf.fit(X_train, y_train)

# Salvar modelo
with open('modelo_ex1.pkl', 'wb') as pickle_file:
    pk.dump(model1, pickle_file)

y_pred = clf.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[33  0  0  0  2  0  0  0  1  0]
 [ 0 27  1  0  2  1  0  0  4  1]
 [ 0  1 32  0  0  0  0  1  1  0]
 [ 0  1  2 30  0  2  0  0  2  0]
 [ 0  0  0  0 29  1  3  2  0  1]
 [ 0  0  0  3  0 34  0  0  0  0]
 [ 0  0  0  0  2  1 32  1  0  0]
 [ 0  0  0  1  1  0  0 33  1  0]
 [ 0  1  0  0  2  0  0  0 31  1]
 [ 0  0  0  1  0  1  0  0  2 32]]
              precision    recall  f1-score   support

           0       1.00      0.92      0.96        36
           1       0.90      0.75      0.82        36
           2       0.91      0.91      0.91        35
           3       0.86      0.81      0.83        37
           4       0.76      0.81      0.78        36
           5       0.85      0.92      0.88        37
           6       0.91      0.89      0.90        36
           7       0.89      0.92      0.90        36
           8       0.74      0.89      0.81        35
           9       0.91      0.89      0.90        36

    accuracy                           0.87       360
   macro avg       

# Exercício 2

In [2]:
from sklearn.ensemble import RandomForestClassifier

clf2a = RandomForestClassifier(n_estimators=100, random_state=42)
model2a = clf2a.fit(X_train, y_train)

# Salvar modelo
with open('modelo_ex21a.pkl', 'wb') as pickle_file:
    pk.dump(model2a, pickle_file)

y_pred2a = clf2a.predict(X_test)

print(confusion_matrix(y_test, y_pred2a))
print(classification_report(y_test, y_pred2a))

[[35  0  0  0  1  0  0  0  0  0]
 [ 0 36  0  0  0  0  0  0  0  0]
 [ 0  0 35  0  0  0  0  0  0  0]
 [ 0  0  0 34  0  0  0  1  2  0]
 [ 0  0  0  0 35  0  0  0  1  0]
 [ 0  0  0  0  0 37  0  0  0  0]
 [ 0  0  0  0  0  0 36  0  0  0]
 [ 0  0  0  0  0  0  0 36  0  0]
 [ 0  2  0  1  0  0  0  1 31  0]
 [ 0  1  0  0  0  1  0  0  0 34]]
              precision    recall  f1-score   support

           0       1.00      0.97      0.99        36
           1       0.92      1.00      0.96        36
           2       1.00      1.00      1.00        35
           3       0.97      0.92      0.94        37
           4       0.97      0.97      0.97        36
           5       0.97      1.00      0.99        37
           6       1.00      1.00      1.00        36
           7       0.95      1.00      0.97        36
           8       0.91      0.89      0.90        35
           9       1.00      0.94      0.97        36

    accuracy                           0.97       360
   macro avg       

In [4]:
import xgboost as xgb

clf2b =  xgb.XGBClassifier(tree_method="hist", early_stopping_rounds=2) 
model2b = clf2b.fit(X_train, y_train, eval_set=[(X_test, y_test)])

# Salvar modelo
with open('modelo_ex21b.pkl', 'wb') as pickle_file:
    pk.dump(model2b, pickle_file)

y_pred2b = clf2b.predict(X_test)

print(confusion_matrix(y_test, y_pred2b))
print(classification_report(y_test, y_pred2b))

[0]	validation_0-mlogloss:1.39540
[1]	validation_0-mlogloss:1.07021
[2]	validation_0-mlogloss:0.85838
[3]	validation_0-mlogloss:0.70738
[4]	validation_0-mlogloss:0.59879
[5]	validation_0-mlogloss:0.51443
[6]	validation_0-mlogloss:0.44744
[7]	validation_0-mlogloss:0.39825
[8]	validation_0-mlogloss:0.35675
[9]	validation_0-mlogloss:0.32266
[10]	validation_0-mlogloss:0.29744
[11]	validation_0-mlogloss:0.27312
[12]	validation_0-mlogloss:0.24955
[13]	validation_0-mlogloss:0.23252
[14]	validation_0-mlogloss:0.22036
[15]	validation_0-mlogloss:0.20657


[16]	validation_0-mlogloss:0.19703
[17]	validation_0-mlogloss:0.18856
[18]	validation_0-mlogloss:0.18145
[19]	validation_0-mlogloss:0.17409
[20]	validation_0-mlogloss:0.16829
[21]	validation_0-mlogloss:0.16348
[22]	validation_0-mlogloss:0.15896
[23]	validation_0-mlogloss:0.15561
[24]	validation_0-mlogloss:0.15333
[25]	validation_0-mlogloss:0.15042
[26]	validation_0-mlogloss:0.14803
[27]	validation_0-mlogloss:0.14521
[28]	validation_0-mlogloss:0.14359
[29]	validation_0-mlogloss:0.14147
[30]	validation_0-mlogloss:0.14040
[31]	validation_0-mlogloss:0.14006
[32]	validation_0-mlogloss:0.13729
[33]	validation_0-mlogloss:0.13622
[34]	validation_0-mlogloss:0.13486
[35]	validation_0-mlogloss:0.13441
[36]	validation_0-mlogloss:0.13390
[37]	validation_0-mlogloss:0.13339
[38]	validation_0-mlogloss:0.13209
[39]	validation_0-mlogloss:0.13154
[40]	validation_0-mlogloss:0.13040
[41]	validation_0-mlogloss:0.12951
[42]	validation_0-mlogloss:0.12874
[43]	validation_0-mlogloss:0.12745
[44]	validation_0-ml